from tkinter import*
import random
import time
root = Tk()
root.title("Cafe Management System")
Tops = Frame(root,bg="white",width = 1600,height=50,relief=SUNKEN)
Tops.pack(side=TOP)
f1 = Frame(root,width = 900,height=700,relief=SUNKEN)
f1.pack(side=LEFT)
f2 = Frame(root ,width = 400,height=700,relief=SUNKEN)
f2.pack(side=RIGHT)
#Time and date
localtime=time.asctime(time.localtime(time.time()))
#Title
lblinfo = Label(Tops, font=( 'times new roman' ,30, 'bold' ),text="Cafe Reputation Management ",fg="red",bd=10,anchor='w',bg='pink')
lblinfo.grid(row=0,column=0)
lblinfo = Label(Tops, font=( 'times new roman' ,20, ),text=localtime,fg="red",anchor=W)
lblinfo.grid(row=1,column=0)
#Calculator
text_Input=StringVar()
operator =""
txtdisplay = Entry(f2,font=('times new roman' ,20,'bold'), textvariable=text_Input , bd=5 ,insertwidth=7 ,bg="pink",justify='right')
txtdisplay.grid(columnspan=4)
def  btnclick(numbers):
    global operator
    operator=operator + str(numbers)
    text_Input.set(operator)
def clrdisplay():
    global operator
    operator=""
    text_Input.set("")
def eqals():
    global operator
    sumup=str(eval(operator))
    text_Input.set(sumup)
    operator = ""
def Ref():
    x=random.randint(12980, 50876)
    randomRef = str(x)
    rand.set(randomRef)
    cof =float(esp.get())
    colice= float(ice.get())
    cob= float(cup.get())
    cofi= float(red.get())
    cochee= float(black.get())
    codr= float(cake.get())
    costofesp = cof*25
    costofice = colice*40
    costofcup = cob*35
    costofred = cofi*50
    costofblack = cochee*50
    costofcake = codr*35
    costofmeal = "Rs.",str('%.2f'% (costofesp +  costofice + costofcup + costofred + costofblack + costofcake))
    PayTax=((costofesp +  costofice + costofcup + costofred + costofblack + costofcake)*0.33)
    Totalcost=(costofesp +  costofice + costofcup + costofred + costofblack + costofcake)
    Ser_Charge=((costofesp +  costofice + costofcup + costofred + costofblack + costofcake)/99)
    Service="Rs.",str('%.2f'% Ser_Charge)
    OverAllCost="Rs.",str( PayTax + Totalcost + Ser_Charge)
    PaidTax="Rs.",str('%.2f'% PayTax)
    Service_Charge.set(Service)
    cost.set(costofmeal)
    Tax.set(PaidTax)
    #Subtotal.set(costofmeal)
    Total.set(OverAllCost)
def qexit():
    root.destroy()
def reset():
    rand.set("")
    esp.set("")
    ice.set("")
    cup.set("")
    red.set("")
    Subtotal.set("")
    Total.set("")
    Service_Charge.set("")
    cake.set("")
    Tax.set("")
    cost.set("")
    black.set("")
#Calculator
btn7=Button(f2,padx=16,pady=16,bd=7, fg="maroon", font=('times new roman', 20 ,'bold'),text="7",bg="pink", command=lambda: btnclick(7) )
btn7.grid(row=2,column=0)
btn8=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="8",bg="pink", command=lambda: btnclick(8) )
btn8.grid(row=2,column=1)
btn9=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="9",bg="pink", command=lambda: btnclick(9) )
btn9.grid(row=2,column=2)
Addition=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="+",bg="pink", command=lambda: btnclick("+") )
Addition.grid(row=2,column=3)
#---------------------------------------------------------------------------------------------
btn4=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="4",bg="pink", command=lambda: btnclick(4) )
btn4.grid(row=3,column=0)
btn5=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="5",bg="pink", command=lambda: btnclick(5) )
btn5.grid(row=3,column=1)
btn6=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="6",bg="pink", command=lambda: btnclick(6) )
btn6.grid(row=3,column=2)
Substraction=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="-",bg="pink", command=lambda: btnclick("-") )
Substraction.grid(row=3,column=3)
#-----------------------------------------------------------------------------------------------
btn1=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="1",bg="pink", command=lambda: btnclick(1) )
btn1.grid(row=4,column=0)
btn2=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="2",bg="pink", command=lambda: btnclick(2) )
btn2.grid(row=4,column=1)
btn3=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="3",bg="pink", command=lambda: btnclick(3) )
btn3.grid(row=4,column=2)
multiply=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="*",bg="pink", command=lambda: btnclick("*") )
multiply.grid(row=4,column=3)
#------------------------------------------------------------------------------------------------
btn0=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="0",bg="pink", command=lambda: btnclick(0) )
btn0.grid(row=5,column=0)
btnc=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text="c",bg="pink", command=clrdisplay)
btnc.grid(row=5,column=1)
btnequal=Button(f2,padx=16,pady=16,bd=4,width = 16, fg="maroon", font=('times new roman', 20 ,'bold'),text="=",bg="pink",command=eqals)
btnequal.grid(columnspan=4)
Decimal=Button(f2,padx=16,pady=16,bd=4, fg="maroon", font=('times new roman', 20 ,'bold'),text=".",bg="pink", command=lambda: btnclick(".") )
Decimal.grid(row=5,column=2)
Division=Button(f2,padx=16,pady=16,bd=4,fg="maroon", font=('times new roman', 20 ,'bold'),text="/",bg="pink", command=lambda: btnclick("/") )
Division.grid(row=5,column=3)
#------------------------------------------------------------------------------------------------
rand = StringVar()
esp = StringVar()
ice = StringVar()
cup = StringVar()
red = StringVar()
Subtotal = StringVar()
Total = StringVar()
Service_Charge = StringVar()
cake = StringVar()
Tax = StringVar()
cost = StringVar()
black = StringVar()

lblreference = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Order No.",fg="red",bd=10,anchor='w',bg='pink')
lblreference.grid(row=0,column=0)
txtreference = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=rand , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtreference.grid(row=0,column=1)
lblesp = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Espresso ",fg="red",bd=10,anchor='w')
lblesp.grid(row=1,column=0)
txtesp = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=esp , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtesp.grid(row=1,column=1)
lblice = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Iced Latte ",fg="red",bd=10,anchor='w')
lblice.grid(row=2,column=0)
txtice = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=ice , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtice.grid(row=2,column=1)
lblcup = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Cappuccino ",fg="red",bd=10,anchor='w')
lblcup.grid(row=3,column=0)
txtcup = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=cup , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtcup.grid(row=3,column=1)
lblred = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Red Velvet Cake ",fg="red",bd=10,anchor='w')
lblred.grid(row=4,column=0)
txtred = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=red , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtred.grid(row=4,column=1)
lblblack = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Black Forest ",fg="red",bd=10,anchor='w')
lblblack.grid(row=5,column=0)
txtblack = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=black , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtblack.grid(row=5,column=1)
lblcake = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Coffee cake ",fg="red",bd=10,anchor='w')
lblcake.grid(row=6,column=0)
txtcake = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=cake , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtcake.grid(row=6,column=1)
#################################################################################################
lblcost = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Total",fg="red",bd=10,anchor='w')
lblcost.grid(row=1,column=2)
txtcost = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=cost , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtcost.grid(row=1,column=3)
lblService_Charge = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Service Charge",fg="red",bd=10,anchor='w')
lblService_Charge.grid(row=3,column=2)
txtService_Charge = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=Service_Charge , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtService_Charge.grid(row=3,column=3)
lblTax = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Tax",fg="red",bd=10,anchor='w')
lblTax.grid(row=5,column=2)
txtTax = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=Tax , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtTax.grid(row=5,column=3)
lblTotal = Label(f1, font=( 'times new roman' ,16, 'bold' ),text="Receipt",fg="red",bd=10,anchor='w')
lblTotal.grid(row=7,column=2)
txtTotal = Entry(f1,font=('times new roman' ,16,'bold'), textvariable=Total , bd=6,insertwidth=4,bg="pink" ,justify='right')
txtTotal.grid(row=7,column=3)
#buttons
btnTotal=Button(f1,padx=16,pady=8, bd=10 ,fg="black",font=('times new roman' ,16,'bold'),width=10, text="TOTAL", bg="pink",command=Ref)
btnTotal.grid(row=6, column=8)
btnreset=Button(f1,padx=16,pady=8, bd=10 ,fg="black",font=('times new roman' ,16,'bold'),width=10, text="RESET", bg="pink",command=reset)
btnreset.grid(row=4, column=8)
btnexit=Button(f1,padx=16,pady=8, bd=10 ,fg="black",font=('times new roman' ,16,'bold'),width=10, text="EXIT", bg="pink",command=qexit)
btnexit.grid(row=2, column=8)
#Gui for the price menu
def price():
    roo = Tk()
    roo.title("Price List")
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="ITEM", fg="black", bd=5)
    lblinfo.grid(row=0, column=0)
    lblinfo = Label(roo, font=('times new roman', 15,'bold'), text="_____________", fg="black", anchor=W)
    lblinfo.grid(row=0, column=2)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="PRICE", fg="black", anchor=W)
    lblinfo.grid(row=0, column=3)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="Espresso", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=1, column=0)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="25", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=1, column=3)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="Iced Latte", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=2, column=0)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="40", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=2, column=3)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="Cappucciono", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=3, column=0)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="35", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=3, column=3)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="Red Velvet cake", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=4, column=0)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="50", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=4, column=3)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="Black Forest", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=5, column=0)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="30", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=5, column=3)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="Coffee cake", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=6, column=0)
    lblinfo = Label(roo, font=('times new roman', 15, 'bold'), text="35", fg="silver",bg='black', anchor=W)
    lblinfo.grid(row=6, column=3)
    roo.mainloop()
btnprice=Button(f1,padx=16,pady=8, bd=10 ,fg="black",font=('ariel' ,16,'bold'),width=10, text="PRICE", bg="pink",command=price)
btnprice.grid(row=8, column=8)
root.mainloop()
